--Number of bank accounts created in a month for a specific bank
SELECT B.BANK_NAME, TO_CHAR(CBA.ACCOUNT_CREATION_DATE, 'MONTH') ACCOUNT_CREATION_MONTH, COUNT(CBA.BANK_ACCOUNT_NUMBER) AS NO_OF_BANK_ACCOUNT
FROM CUSTOMER_BANK_ACCOUNT CBA JOIN BANK B ON CBA.BANK_ID = B.BANK_ID
GROUP BY B.BANK_NAME, TO_CHAR(CBA.ACCOUNT_CREATION_DATE, 'MONTH');

--Total money sent from and received for a bank account
WITH MONEY_SENT_FROM_BANK_ACCOUNT AS
( 
    SELECT CBA.BANK_ACCOUNT_NUMBER AS ACCOUNT_NUMBER, SUM(T.TRANSACTION_AMOUNT) AS SENT_AMOUNT 
    FROM CUSTOMER_BANK_ACCOUNT CBA, TRANSACTION T, SENDER_RECEIVER_PAYMENT_TOKEN SRPT
    WHERE CBA.BANK_ACCOUNT_NUMBER = SRPT.SENDER_BANK_ACCOUNT_NUMBER AND SRPT.TOKEN_ID = T.SENDER_RECEIVER_PAYMENT_TOKEN_ID GROUP BY CBA.BANK_ACCOUNT_NUMBER
),
MONEY_RECEIVED_FROM_BANK_ACCOUNT AS
(
    SELECT CBA.BANK_ACCOUNT_NUMBER AS ACCOUNT_NUMBER, SUM(T.TRANSACTION_AMOUNT) AS RECEIVED_AMOUNT 
    FROM CUSTOMER_BANK_ACCOUNT CBA, TRANSACTION T, SENDER_RECEIVER_PAYMENT_TOKEN SRPT
    WHERE CBA.BANK_ACCOUNT_NUMBER = SRPT.RECEIVER_BANK_ACCOUNT_NUMBER AND SRPT.TOKEN_ID = T.SENDER_RECEIVER_PAYMENT_TOKEN_ID GROUP BY CBA.BANK_ACCOUNT_NUMBER
)
SELECT CBA.BANK_ACCOUNT_NUMBER, MSFBA.SENT_AMOUNT AS MONEY_SENT, MRFBA.RECEIVED_AMOUNT AS MONEY_RECEIVED
FROM CUSTOMER_BANK_ACCOUNT CBA, MONEY_SENT_FROM_BANK_ACCOUNT MSFBA, MONEY_RECEIVED_FROM_BANK_ACCOUNT MRFBA
WHERE CBA.BANK_ACCOUNT_NUMBER = MSFBA.ACCOUNT_NUMBER AND CBA.BANK_ACCOUNT_NUMBER = MRFBA.ACCOUNT_NUMBER;
        
--State wise list of customers with active and inactive accounts
SELECT C.CUSTOMER_ID, C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME, CA.STATE, C.STATUS 
FROM CUSTOMER C JOIN CUSTOMER_ADDRESS CA ON C.CUSTOMER_ID = CA.CUSTOMER_ID
ORDER BY CA.STATE, C.STATUS; 

--Number of transactions that were done business to business, business to individual, individual to business, individual to individual
WITH SENDER_TYPE_MAPPING AS
(
    SELECT T.TRANSACTION_ID AS TRANSID, C.TYPE_OF_USER AS SENDER_TYPE 
    FROM CUSTOMER C, CUSTOMER_BANK_ACCOUNT CBA, SENDER_RECEIVER_PAYMENT_TOKEN SRPT, TRANSACTION T
    WHERE T.SENDER_RECEIVER_PAYMENT_TOKEN_ID = SRPT.TOKEN_ID AND SRPT.SENDER_BANK_ACCOUNT_NUMBER = CBA.BANK_ACCOUNT_NUMBER AND CBA.CUSTOMER_ID = C.CUSTOMER_ID
),
    RECEIVER_TYPE_MAPPING AS
(
    SELECT T.TRANSACTION_ID AS TRANSID, C.TYPE_OF_USER AS RECEIVER_TYPE 
    FROM CUSTOMER C, CUSTOMER_BANK_ACCOUNT CBA, SENDER_RECEIVER_PAYMENT_TOKEN SRPT, TRANSACTION T
    WHERE T.SENDER_RECEIVER_PAYMENT_TOKEN_ID = SRPT.TOKEN_ID AND SRPT.RECEIVER_BANK_ACCOUNT_NUMBER = CBA.BANK_ACCOUNT_NUMBER AND CBA.CUSTOMER_ID = C.CUSTOMER_ID
),
    TRANASCTION_TYPE_MAPPING AS
(
    SELECT STM.TRANSID AS TRANSID, CASE WHEN STM.SENDER_TYPE = 'INDIVIDUAL' AND RTM.RECEIVER_TYPE = 'INDIVIDUAL' THEN 'INDIVIDUAL TO INDIVIDUAL'
                                        WHEN STM.SENDER_TYPE = 'INDIVIDUAL' AND RTM.RECEIVER_TYPE = 'BUSINESS' THEN 'INDIVIDUAL TO BUSINESS'
                                        WHEN STM.SENDER_TYPE = 'BUSINESS' AND RTM.RECEIVER_TYPE = 'INDIVIDUAL' THEN 'BUSINESS TO INDIVIDUAL'
                                        WHEN STM.SENDER_TYPE = 'BUSINESS' AND RTM.RECEIVER_TYPE = 'BUSINESS' THEN 'BUSINESS TO BUSINESS'
                                   END AS TRASNACTION_TYPE
    FROM SENDER_TYPE_MAPPING STM, RECEIVER_TYPE_MAPPING RTM 
    WHERE STM.TRANSID = RTM.TRANSID
)
SELECT TTM.TRASNACTION_TYPE, COUNT(TTM.TRANSID) FROM TRANASCTION_TYPE_MAPPING TTM GROUP BY TTM.TRASNACTION_TYPE;


--[Internal view] Masking token ID, account number for customer support representative
SELECT  '*****' || SUBSTR(TO_CHAR(SRPT.TOKEN_ID),-4,4) AS TOKEN_ID, 
        '*****' || SUBSTR(TO_CHAR(SRPT.SENDER_BANK_ACCOUNT_NUMBER),-4,4) AS SENDER_BANK_ACCOUNT_NUMBER, 
        SC.FIRST_NAME || ' ' || SC.LAST_NAME AS SENDER_NAME, 
        '*****' || SUBSTR(TO_CHAR(SRPT.RECEIVER_BANK_ACCOUNT_NUMBER),-4,4) AS RECEIVER_BANK_ACCOUNT_NUMBER, 
        RC.FIRST_NAME || ' ' || RC.LAST_NAME AS RECEIVER_NAME, 
        SRPT.TOKEN_STATUS AS TOKEN_STATUS
FROM SENDER_RECEIVER_PAYMENT_TOKEN SRPT
    JOIN CUSTOMER_BANK_ACCOUNT SCBA ON SRPT.SENDER_BANK_ACCOUNT_NUMBER = SCBA.BANK_ACCOUNT_NUMBER
    JOIN CUSTOMER SC ON SCBA.CUSTOMER_ID = SC.CUSTOMER_ID
    JOIN CUSTOMER_BANK_ACCOUNT RCBA ON SRPT.RECEIVER_BANK_ACCOUNT_NUMBER = RCBA.BANK_ACCOUNT_NUMBER
    JOIN CUSTOMER RC ON RCBA.CUSTOMER_ID = RC.CUSTOMER_ID;