SELECT * from DATABASE_ADMIN_USER.CUSTOMER;
SELECT * from DATABASE_ADMIN_USER.CUSTOMER_ADDRESS;
SELECT * from DATABASE_ADMIN_USER.BANK;
SELECT * from DATABASE_ADMIN_USER.BUSINESS_DETAIL;
SELECT * from DATABASE_ADMIN_USER.TOKEN_VIEW_DATA;