exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'JOHN','SMITH','20-FEB-1969', 88762673, 'JOHN.SMITH@NEU.EDU', 'INDIVIDUAL', 'ACTIVE', 637373737);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (1, 15, '20 Malibu Street', 'Los Angeles', 'CA', 025314);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ('TOM','JONES','12-MAR-1988', 21212189, 'TOM.JONES@NEU.EDU', 'INDIVIDUAL', 'ACTIVE', 876537818);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (2, 2, '24 Brook Street', 'Boston', 'MA', 02445);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ('JAMES','WILLIAMSON','07-FEB-1996', 767366362, 'JAMES.WILLIAMSON@NEU.EDU', 'INDIVIDUAL', 'ACTIVE', 783728732);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (3, 4, '1126 Boylston Street', 'Boston', 'MA', 02845);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ('TRESSY','DSOUZA','06-JUN-1990', 8988221212, 'TRESSY.DSOUZA@NEU.EDU', 'INDIVIDUAL', 'ACTIVE', 653535262);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (4, 7, '89 Peter Avenue', 'New York', 'NY', 02957);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'TIMMOTHY','JACKSON','23-JUN-1982', 8995486632, 'TIMOTHY.JACKSON@NEU.EDU', 'INDIVIDUAL', 'ACTIVE', 653515897);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (5, 2, '67 Commonwealth Avenue', 'Los Angeles', 'CA', 02365);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'JOHNSON','SMITH','20-FEB-1969', 88762673, 'JOHNSON.SMITH@NEU.EDU', 'BUSINESS', 'ACTIVE', 637373738);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (6, 15, '15 Malibu Street', 'Los Angeles', 'CA', 025314);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.BUSINESSDETAILINSERT(6, 'TARGET', 546);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ('TOMSON','JONES','12-MAR-1988', 21212189, 'TOMSON.JONES@NEU.EDU', 'BUSINESS', 'ACTIVE', 876537819);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (7, 2, '25 Brook Street', 'Boston', 'MA', 02445);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.BUSINESSDETAILINSERT(7, 'AMAZON', 547);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'JAMESON','WILLIAMSON','07-FEB-1996', 767366362, 'JAMESON.WILLIAMSON@NEU.EDU', 'BUSINESS', 'ACTIVE', 783728733);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (8, 4, '1127 Boylston Street', 'Boston', 'MA', 02845);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.BUSINESSDETAILINSERT(8, 'WHOLEFOOD', 548);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'TRESSYSON','DSOUZA','06-JUN-1990', 8988221212, 'TRESSYSON.DSOUZA@NEU.EDU', 'BUSINESS', 'ACTIVE', 653535263);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (9, 7, '90 Peter Avenue', 'New York', 'NY', 02957);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.BUSINESSDETAILINSERT(9, 'PRICERITE', 549);

exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERINSERT ( 'TIMMOTHYSON','JACKSON','23-JUN-1982', 8995486632, 'TIMOTHYSON.JACKSON@NEU.EDU', 'BUSINESS', 'ACTIVE', 653515898);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.CUSTOMERADDRESSINSERT (10, 2, '68 Commonwealth Avenue', 'Los Angeles', 'CA', 02365);
exec DATABASE_ADMIN_USER.CUSTOMER_PACKAGE.BUSINESSDETAILINSERT(10, 'COSCO', 550);

COMMIT;

exec DATABASE_ADMIN_USER.BANK_PACKAGE.BANKINSERT('Santander Bank', 'Jack', 'Smith', 'support@santander.com', 8756732415);
exec DATABASE_ADMIN_USER.BANK_PACKAGE.BANKINSERT('Chase Bank', 'Anita', 'Deb', 'support@chase.com', 8574536789);
exec DATABASE_ADMIN_USER.BANK_PACKAGE.BANKINSERT('Bank of America', 'Dhawal', 'Gandi', 'support@bofa.com', 6176258907);
exec DATABASE_ADMIN_USER.BANK_PACKAGE.BANKINSERT('National Bank', 'Prithvi', 'Negi', 'support@nationalbank.com', 8675642908);

COMMIT;

exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (1, 2, 'ACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (2, 3, 'INACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (3, 4, 'ACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (4, 1, 'INACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (5, 2, 'ACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (6, 2, 'INACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (7, 3, 'ACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (8, 4, 'INACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (9, 1, 'ACTIVE');
exec DATABASE_ADMIN_USER.BANK_ACCOUNT_PACKAGE.ACCOUNTINSERT (10, 2, 'INACTIVE');

COMMIT;

exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1000, 1002, 'ACTIVE', '4');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1000, 1004, 'ACTIVE', '5');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1002, 1006, 'ACTIVE', '2');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1006, 1008, 'ACTIVE', '8');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1003, 1000, 'INACTIVE', '11');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT (1008, 1000, 'ACTIVE', '7');
exec DATABASE_ADMIN_USER.TOKEN_PACKAGE.TOKENINSERT( 1002, 1008,'ACTIVE', '12');

COMMIT;

exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT( 1000, 'AA78DH87', 100000, 'PENDING', 'Rent payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT( 1000, 'HW89KK09', 19800, 'PENDING', 'Gas payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT(1002, 'SE09OK98', 1000, 'PENDING', 'Phone EMI');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT(1002, 'AA78DDSAH87', 100000, 'PENDING', 'Rent payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT(1005, 'HW89KKQW09', 19800, 'PENDING', 'Gas payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT( 1005, 'SE09OKEWQ98', 1000, 'PENDING', 'Phone EMI');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT( 1005, 'AA78DSADH87', 100000, 'PENDING', 'Rent payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT( 1003, 'HW8DAS9KK09', 19800, 'PENDING', 'Gas payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT (1003, 'SE09ASDOK98', 1000, 'PENDING', 'Phone EMI');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT ( 1003, 'AA78ASDDH87', 100000, 'PENDING', 'Rent payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT (1001, 'HW89KKSAD09', 19800, 'PENDING', 'Gas payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT (1001, 'SE09OSADK98', 1000, 'PENDING', 'Phone EMI');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT (1001, 'AA78DHASD87', 100000, 'PENDING', 'Rent payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT (1002, 'HW89KSADK09', 19800, 'PENDING', 'Gas payment');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT ( 1002, 'SE09OSADSAK98', 1000, 'PENDING', 'Phone EMI');
exec DATABASE_ADMIN_USER.TRANSACTION_PACKAGE.TRANSACTIONINSERT ( 1002, 'AA78DASDH87', 100000, 'PENDING', 'Rent payment');

COMMIT;